server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl   #导出外部日志文件
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #在黑窗口打印日志文件

  mapper-locations: classpath:com/zzh/mapper/*.xml
  type-aliases-package: com.zzh.mapper



log:
  path: /logs/IrailLog
  level: TRACE    #DEBUG
  name:
    info: IrailInfo
    error: IrailError
    sql: IrailSql
